api/pom.xml, api/src/main/java/io/keploy/client/GrpcClient.java, core/pom.xml, integration/pom.xml, integration/src/main/java/TestInstrumentaion.java, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/src/main/resources/META-INF/MANIFEST.MF, models/pom.xml, models/src/main/java/io/keploy/grpc/stubs/Service.java, pom.xml
- Changed java version in every pom.xml file.
- Used java.net.HttpURLConnection (supports java8) to send custom request.
=> feat: add support for java 8

core/src/main/java/io/keploy/regression/keploy/AppConfig.java, core/src/main/java/io/keploy/regression/keploy/Keploy.java, core/src/main/java/io/keploy/regression/keploy/ServerConfig.java, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/pom.xml, models/src/main/java/io/keploy/grpc/stubs/Service.java, pom.xml
- added plugins for sonatype to deploy on **_maven central_** .
- set some default values like `APP_NAME`, `APP_PORT` , `KEPLOY_URL` so that user can use default keploy config .
=> refactor: make changes in pom for maven central deployment

api/src/main/java/io/keploy/service/GrpcService.java, common/pom.xml, common/src/main/java/io/keploy/utils/HaltThread.java, integration/pom.xml, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/pom.xml, keploy-sdk/src/main/resources/META-INF/MANIFEST.MF, pom.xml
- CountDownLatch waits for the threads to complete their execution.
=> feat: add CountDownLatch to run test mode using command

api/pom.xml, api/src/main/java/io/keploy/service/GrpcService.java, common/src/main/java/io/keploy/utils/GenericResponseWrapper.java, core/src/main/java/io/keploy/regression/context/Context.java, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/src/main/resources/META-INF/MANIFEST.MF
api: Change HTTP client to okhttp to get the concurrent requests feature. 
common: Change response wrapper to ensure getting a response from the map from the GetResp method in simulate.
=> fix: change http client, responsewrapper due to concurrency behaviour

api/src/main/java/io/keploy/service/GrpcService.java, core/src/main/java/io/keploy/regression/keploy/AppConfig.java, integration/src/main/java/io/keploy/servlet/middleware.java
=> refactor: make de-noise call optional with use of env variable

api/pom.xml, api/src/main/java/io/keploy/service/GrpcService.java, common/src/main/java/io/keploy/utils/GenericResponseWrapper.java, core/pom.xml, core/src/main/java/io/keploy/regression/keploy/Keploy.java, integration/pom.xml, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/pom.xml, keploy-sdk/src/main/resources/META-INF/MANIFEST.MF, models/pom.xml, models/src/main/java/io/keploy/grpc/stubs/RegressionServiceGrpc.java, models/src/main/java/io/keploy/grpc/stubs/Service.java, pom.xml
=> refactor: upgrade obsolete dependencies and refactor

README.md, integration/src/main/java/io/keploy/servlet/middleware.java
=> refactor: add docs to use denoise as optional parameter

README.md, api/src/main/java/io/keploy/service/GrpcService.java, core/src/main/java/io/keploy/regression/keploy/AppConfig.java, core/src/main/java/io/keploy/regression/keploy/ServerConfig.java, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/src/main/resources/META-INF/MANIFEST.MF, models/src/main/java/io/keploy/grpc/stubs/Service.java
Signed-off-by: iamskp99 <iamskp99@gmail.com>
This PR is for this issue: https://github.com/keploy/java-sdk/issues/27
- Set the default value of denoise as 'false'.
- Moved the de-noise field from appConfig to serverConfig.
=> refactor: move de-noise field from appConfig to serverConfig

api/src/main/java/io/keploy/service/GrpcService.java
- Final result of test run was showing true result even after some of the testcases failed because
inside loop everytime a new `countdownlatch` was created. 
- This got fixed by initializing the `countdownlatch` with _size = no of tests_ outside the loop.
- This fixes #33 
=> fix(api): final result show true even after some tests failed

api/src/main/java/io/keploy/service/GrpcService.java
=> feat(api): add support for optional async testing

README.md
=> refactor(readme): refer instruction to start keploy server

api/pom.xml, api/src/main/java/io/keploy/service/GrpcService.java, integration/pom.xml, integration/src/main/java/io/keploy/servlet/middleware.java, keploy-sdk/pom.xml
=> refactor: set protocol type and update pom files

api/src/main/java/io/keploy/service/GrpcService.java, integration/pom.xml, models/pom.xml, models/src/main/java/io/keploy/grpc/proto/service.proto, models/src/main/java/io/keploy/grpc/stubs/RegressionServiceGrpc.java, models/src/main/java/io/keploy/grpc/stubs/Service.java, pom.xml
- Renamed path to TestCasePath in proto file.
- Update some dependency versions
=> refactor: rename path to testcasepath

keploy-sdk/src/main/resources/META-INF/MANIFEST.MF
=> refactor: rewrite MANIFEST.MF file to update deps versions

api/src/main/java/io/keploy/service/GrpcService.java, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> refactor: make change for condition in header response

README.md, integration/src/main/java/io/keploy/servlet/middleware.java
=> refactor: changed directory to store exported testcases

api/src/main/java/io/keploy/service/GrpcService.java, integration/src/main/java/io/keploy/servlet/middleware.java, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> logs:improved crash logs during failure with keploy

api/src/main/java/io/keploy/service/GrpcService.java, models/src/main/java/io/keploy/grpc/proto/service.proto, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> refactor(api): add testcase path in start request

README.md, integration/src/main/java/io/keploy/servlet/KeployMiddleware.java
- Rename custom test and mock path set by user by env variable.
- Update readme to use the keploy java-sdk independent of spring
=> refactor:update readme and rename custom test & mock path

README.md, agent/src/main/resources/log4j2.properties, api/src/main/resources/log4j2.properties, core/src/main/resources/log4j2.properties, integration/src/main/resources/log4j2.properties
- Update readme file, add usage instructions for JAVA EE application.
- Add log42j.properties for logging in non-spring application.
=> fix:add log42j configuration to fix logging

api/src/main/java/io/keploy/service/GrpcService.java, integration/src/main/java/io/keploy/httpClients/OkHttpInterceptor_Kotlin.java, integration/src/main/java/io/keploy/servlet/KeployMiddleware.java
- Change log level from error to info when no directory containing test cases found.
=> refactor(api): change log level to info when no tests directory found 

api/src/main/java/io/keploy/service/GrpcService.java
=> fix: add option to configure app delay during test mode for slow apps

agent/src/main/java/io/keploy/advice/ksql/DataBaseMetaData_Advice.java, agent/src/main/java/io/keploy/agent/KAgent.java, integration/src/main/java/io/keploy/ksql/KConnection.java, integration/src/main/java/io/keploy/ksql/KDatabaseMetaData.java, integration/src/main/java/io/keploy/ksql/KPreparedStatement.java, integration/src/main/java/io/keploy/ksql/KResultSet.java, integration/src/main/java/io/keploy/ksql/KStatement.java, keploy-sdk/src/main/resources/META-INF/MANIFEST.MF, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> fix: intialize databasemeta data in advice

agent/src/main/java/io/keploy/advice/CustomGoogleResponseAdvice.java, agent/src/main/java/io/keploy/agent/KAgent.java, common/src/main/java/io/keploy/utils/CustomHttpResponses.java, integration/pom.xml, integration/src/main/java/io/keploy/googleMaps/GoogleMapsInterceptor.java
- Add an interceptor for mocking google maps API calls.
- Related Issue #81
=> feat: add support for mocking feature of google maps services

README.md, integration/src/main/java/io/keploy/ksql/KConnection.java, integration/src/main/java/io/keploy/ksql/KDriver.java, integration/src/main/java/io/keploy/ksql/KPreparedStatement.java, integration/src/main/java/io/keploy/ksql/KResultSet.java, integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java
=> feat(mock): add mocks for h2 requests made during API calls

agent/src/main/java/io/keploy/advice/CustomGoogleResponseAdvice.java, agent/src/main/java/io/keploy/agent/KAgent.java, api/src/main/java/io/keploy/service/GrpcService.java, integration/src/main/java/io/keploy/googleMaps/GoogleMapsInterceptor.java, integration/src/main/java/io/keploy/httpClients/ApacheInterceptor.java, integration/src/main/java/io/keploy/httpClients/OkHttpInterceptor_Kotlin.java
- Handle condition when application uses different okhttp version.
- Improve some logging in the integration module.
=> fix: handle condition for different okhttp version

agent/src/main/java/io/keploy/advice/ksql/RegisterDriverAdvice.java, agent/src/main/java/io/keploy/advice/ksql/RegisterDriverAdvice_Interceptor.java
=> refactor: add dialect for oracle driver in advice

api/src/main/java/io/keploy/service/GrpcService.java, common/src/main/java/io/keploy/utils/MagicBytes.java, common/src/main/java/io/keploy/utils/MultipartContent.java, common/src/main/java/io/keploy/utils/Utility.java, core/src/main/java/io/keploy/regression/keploy/AppConfig.java, integration/pom.xml, integration/src/main/java/io/keploy/httpClients/ApacheInterceptor.java, integration/src/main/java/io/keploy/ksql/KCallableStatement.java, integration/src/main/java/io/keploy/servlet/KeployMiddleware.java, models/src/main/java/io/keploy/grpc/proto/service.proto, models/src/main/java/io/keploy/grpc/stubs/Service.java
- Changed HTTP request and response spec in proto file.
=> feat: add support for multipart requests and binary response

README.md, integration/src/main/java/io/keploy/ksql/KResultSet.java, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> feat(KResultSet): add parser for multiple time and date formats

api/src/main/java/io/keploy/service/GrpcService.java, common/src/main/java/io/keploy/utils/Utility.java, integration/src/main/java/io/keploy/httpClients/ApacheInterceptor.java, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> fix: folder was not being created in get request

api/src/main/java/io/keploy/service/GrpcService.java, integration/pom.xml, integration/src/main/java/io/keploy/googleMaps/GoogleMapsInterceptor.java, integration/src/main/java/io/keploy/httpClients/OkHttpInterceptor_Kotlin.java
=> refactor: downgrade okhttp version in integration module

agent/pom.xml, integration/src/main/java/io/keploy/ksql/KConnection.java, integration/src/main/java/io/keploy/ksql/KDriver.java, integration/src/main/java/io/keploy/ksql/KResultSet.java, keploy-sdk/pom.xml, pom.xml
=> refactor(logging): add some logging and checks in ksql

integration/src/main/java/io/keploy/ksql/KCallableStatement.java, integration/src/main/java/io/keploy/ksql/KConnection.java, integration/src/main/java/io/keploy/ksql/KDatabaseMetaData.java, integration/src/main/java/io/keploy/ksql/KResultSet.java
=> fix(dbmeta): wrap some methods to avoid actual calls during test

keploy-sdk/pom.xml
=> refactor: add fat jar in keploy-sdk module

agent/pom.xml, agent/src/main/java/io/keploy/advice/CustomGoogleResponseAdvice.java, agent/src/main/java/io/keploy/agent/KAgent.java, api/src/main/java/io/keploy/service/GrpcService.java, integration/src/main/java/io/keploy/googleMaps/CustomHttpResponses.java, integration/src/main/java/io/keploy/googleMaps/GoogleMapsInterceptor.java, integration/src/main/java/io/keploy/ksql/KResultSet.java, integration/src/main/java/io/keploy/servlet/KeployMiddleware.java, keploy-sdk/pom.xml, pom.xml
- Refactor some dependencies and moved some classes in their relevant module.
=> refactor: some refactor of dependency and classes

integration/src/main/java/io/keploy/ksql/KCallableStatement.java, integration/src/main/java/io/keploy/ksql/KConnection.java, integration/src/main/java/io/keploy/ksql/KDriver.java, integration/src/main/java/io/keploy/ksql/KParameterMetaData.java, integration/src/main/java/io/keploy/ksql/KPreparedStatement.java, integration/src/main/java/io/keploy/ksql/KResultSet.java, integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java, integration/src/main/java/io/keploy/ksql/KSavepoint.java, integration/src/main/java/io/keploy/ksql/KStatement.java
=> refactor: add remaining null checks and logs in ksql

integration/src/main/java/io/keploy/ksql/KResultSet.java, integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java
=> refactor: wrap getStatement in KResultSet

common/src/main/java/io/keploy/utils/ProcessSQL.java, integration/src/main/java/io/keploy/ksql/KCallableStatement.java, integration/src/main/java/io/keploy/ksql/KConnection.java, integration/src/main/java/io/keploy/ksql/KResultSet.java, integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java
=> refactor: change extract meta from KResultSet to KPreparedStatement

integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java
=> refactor: add support for getColumnLabel in KResultSetMetaData

integration/src/main/java/io/keploy/httpClients/ApacheInterceptor.java
- Checksum headers are essential to check data integrity, the corruptness of raw data, etc. since keploy generated mocks are editable, and little to no change in these mocks leads to differences in the checksum.
- Hence removed the checksum headers of the apache response in the ApacheInterceptor during test mode.
=> fix(integration): remove checksum headers of apache response in test mode

integration/src/main/java/io/keploy/ksql/KResultSet.java
=> refactor: wrapped some method and fix wasnull error

integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java
- Get precision method was not returning anything during test mode.
=> fix(ksql): return value of precision in test mode

api/src/main/java/io/keploy/service/GrpcService.java, models/src/main/java/io/keploy/grpc/proto/service.proto, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> fix: add changes in grpc proto to compliance with go server

README.md, integration/src/main/java/io/keploy/ksql/KResultSetMetaData.java
Previously the version was documented as 1.2.2, to which the latest version 1.2.5 is added.
=> Updated the agent jar version

.github/PULL_REQUEST_TEMPLATE.md
Adding template for pull request
=> Adding PULL_REQUEST_TEMPLATE

README.md, agent/src/main/java/io/keploy/agent/KAgent.java, api/pom.xml, api/src/main/java/io/keploy/service/GrpcService.java, integration/src/main/java/io/keploy/redis/jedis/KConnection.java
`NA`
- Remove commented code and change log level in `KConnection` of `redis`.
`NA`
=> refactor: remove some commented code

integration/pom.xml, integration/src/main/java/io/keploy/redis/jedis/KConnection.java, integration/src/main/java/io/keploy/redis/jedis/RedisCustomSerializer.java
- fixed spring dependency problem in Redis
fixed spring dependency problem in Redis
=> fixed spring dependency problem in redis

README.md, integration/pom.xml, keploy-sdk/pom.xml
- Old commands to run java agent was not working, hence updated it.
- Add updated commands in readMe file
`NA`
=> docs: update command to run application using agent

api/src/main/java/io/keploy/service/GrpcService.java, integration/src/main/java/io/keploy/servlet/KeployMiddleware.java, models/src/main/java/io/keploy/grpc/stubs/Service.java
- Unable to record test cases when a user doesn't provide any filter regex.
- Fix this issue by changing some conditions in the function where we are checking that, is the test case valid to be recorded.
`NA`
=> fix(api,servlet): unable to record testcases when empty filter regex

README.md
- Since sonatype has made changes to the website , previous link is not redirecting to download section of agents .
=> doc: update the link for keploy agent download 

README.md, api/src/main/java/io/keploy/service/GrpcService.java, models/src/main/java/io/keploy/grpc/proto/service.proto, models/src/main/java/io/keploy/grpc/stubs/Service.java
=> feat(GrpcService): add app name field in proto to configure histCfg

integration/src/main/java/io/keploy/ksql/KDatabaseMetaData.java
This method is used to get the database product name, in test mode it was failing since it was not implemented correctly.
=> fix:implement getDatabaseProductName() method of KDatabaseMetaData

integration/src/main/java/io/keploy/ksql/KDriver.java
=> feat: register mysql.jdbc.Driver class with Kdriver

agent/src/main/java/io/keploy/advice/ksql/RegisterDriverAdvice.java, agent/src/main/java/io/keploy/advice/ksql/RegisterDriverAdvice_Interceptor.java, integration/src/main/java/io/keploy/ksql/KDatabaseMetaData.java
=> feat: add hibernate dialects for mysql if user has not set by default

models/src/main/java/io/keploy/grpc/stubs/Service.java, v2/src/main/java/io/keploy/Keploy.java
=> refactor: change run command variable to jar path 
